### ISSUE TITLE
Stubs.swift file not found..

### ISSUE THREAD

**Issue by TnasuH** [alfianlosari/stocksapptutorial#1]
- Stubs.swift files not found in project (part 2).. Could you add it?

- Value of type 'XCAStocksAPI' has no member 'searchTicker' in XCAStocksExec.swift file (part 1). So, can you rename searchTicker to searchTickers in XCAStocksExec.swift file

**Comment by alfianlosari** [comment]
Thanks for reporting. I have fixed those 2 points 🙏🏻
